#!/bin/env python
# Copyright 2010 Robert Spanton
# This file is part of compd.
#
# compd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# compd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
import gobject, glib, sys, os

# Augment the import path with our own
sys.path.append( os.path.dirname( os.path.abspath(__file__) ) )

import workers
from vartree import VarTree

def test_fn(val):
    print "test_fn", val

# # TODO: Store vars in MySQL

if __name__ == "__main__":
    root = VarTree("sr")
    loop = gobject.MainLoop()
    main_context = loop.get_context()

    # Initialise all the workers
    workers = [ x(root) for x in workers.workers ]

    VarTree.subscribe( root, "sr.clock.event_time", test_fn )
    loop.run()
