#!/bin/env python
# Copyright 2010 Robert Spanton
# This file is part of compd.
#
# compd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# compd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
import gobject, glib, sys, os

# Augment the import path with our own
sys.path.append( os.path.dirname( os.path.abspath(__file__) ) )

import workers, interfaces
from vartree import PubSubDict

if __name__ == "__main__":
    root = PubSubDict( desc = "Root of the tree" )
    loop = gobject.MainLoop()
    main_context = loop.get_context()

    # Initialise all the workers
    w = [ x(root) for x in workers.workers ]

    # Same for the interfaces
    ifs = [ x(root) for x in interfaces.interfaces ]

    loop.run()
